diary/urls.py
from django.urls import path, register_converter

from . import converters, views


app_name = 'diary'

register_converter(converters.ISO8601DateConverter, 'date')
register_converter(converters.DiaryOwnerConverter, 'owner')

urlpatterns = [
    # views for creation
    path('neues_tagebuch/', views.new_diary_view, name='new_diary'),
    path('neuer_eintrag/', views.new_entry_view, name='new_entry'),
    path('neuer_ort/', views.new_location_view, name='new_location'),
    path('neues_tag/', views.new_tag_view, name='new_tag'),

    # views for diary (owner)
    path('besitzer/', views.owner_list_view, name='owner_list'),
    path('besitzer/<owner:handle>/', views.owner_detail_view,
         name='owner_detail'),
    path('besitzer/<owner:handle>/bearbeiten/', views.edit_owner_view,
         name='edit_owner'),
    path('besitzer/<owner:handle>/loeschen/', views.delete_owner_view,
         name='delete_owner'),

    # views for diary entryies
    path('eintraege/', views.entry_list_view, name='entry_list'),
    path('<owner:handle>/<date:date>/', views.entry_detail_view,
         name='entry_detail'),
    path('<owner:handle>/<date:date>/bearbeiten/', views.edit_entry_view,
         name='edit_entry'),
    path('<owner:handle>/<date:date>/loeschen/', views.delete_entry_view,
         name='delete_entry'),

    # views for locations
    path('orte/', views.location_list_view, name='location_list'),
    path('orte/<slug:slug>/', views.location_detail_view,
         name='location_detail'),
    path('orte/<slug:slug>/bearbeiten/', views.edit_location_view,
         name='edit_location'),
    path('orte/<str:name>/loeschen/', views.delete_location_view,
         name='delete_location'),

    # views for tags
    path('tags/', views.tag_list_view, name='tag_list'),
    path('tags/<str:name>/', views.tag_detail_view, name='tag_detail'),
    path('tags/<str:name>/bearbeiten/', views.edit_tag_view,
         name='edit_tag'),
    path('tags/<str:name>/loeschen/', views.delete_tag_view,
         name='delete_tag'),

    path('', views.recent_changes_view, name='index'),
]

webdiary/urls.py
from django.contrib import admin
from django.urls import include, path

from diary import views


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('api/locations/', views.get_locations, name='api_locations'),
    path('api/tags/', views.get_tags, name='api_tags'),
    path('', include('diary.urls')),
]

diary/forms.py
from django import forms
from tinymce.widgets import TinyMCE

from .models import DiaryEntry, DiaryOwner, Location, Tag


class CreateDiaryOwnerForm(forms.ModelForm):
    required_css_class = 'required'

    class Meta:
        model = DiaryOwner
        exclude = ['handle', 'place_of_birth', 'time_of_birth']
        labels = {
            'first_name': 'Vorname',
            'middle_name': 'Zweite(r) Vorname(n)',
            'last_name': 'Nachname',
            'birthday': 'Geburtsdatum',
        }


class DiaryEntryForm(forms.ModelForm):
    required_css_class = 'required'

    content = forms.CharField(label='Eintrag', widget=TinyMCE)
    owner = forms.ModelChoiceField(DiaryOwner.objects.all(),
                                   to_field_name='handle',
                                   label='Tagebuch von',)

    class Meta:
        model = DiaryEntry
        exclude = ['creation_time']
        fields = [
            'owner',
            'title',
            'date',
            'locations',
            'tags',
            'content',
        ]
        labels = {
            'title': 'Titel',
            'date': 'Datum',
            'locations': 'Ort(e)',
            'tags': 'Tag(s)',
        }

    def clean(self):
        cleaned_data = super().clean()

        owner = cleaned_data.get('owner')
        locations = cleaned_data.get('locations')
        tags = cleaned_data.get('tags')

        if locations:
            for location in locations:
                if location.owner != owner:
                    error_message = ("Der angegebene Ort {} gehört nicht zum "
                                     "Tagebuch von {} sondern zum Tagebuch "
                                     "von {}.").format(location, owner,
                                                       location.owner)
                    raise forms.ValidationError(error_message)

        if tags:
            for tag in tags:
                if tag.owner != owner:
                    error_message = ("Das angegebene Tag {} gehört nicht zum "
                                     "Tagebuch von {} sondern zum Tagebuch "
                                     "von {}.").format(tag, owner, tag.owner)
                    raise forms.ValidationError(error_message)


class LocationForm(forms.ModelForm):
    required_css_class = 'required'

    owner = forms.ModelChoiceField(DiaryOwner.objects.all(),
                                   to_field_name='handle',
                                   label='Tagebuch von',)

    class Meta:
        model = Location
        exclude = ['slug']
        labels = {
            'name': 'Name',
            'latitude': 'Breitengrad',
            'longitude': 'Längengrad',
            'postal_code': 'PLZ',
            'street': 'Straße',
            'house_number': 'Hausnummer',
            'city': 'Ort',
            'description': 'Beschreibung',
        }


class TagForm(forms.ModelForm):
    required_css_class = 'required'

    owner = forms.ModelChoiceField(DiaryOwner.objects.all(),
                                   to_field_name='handle',
                                   label='Tagebuch von',)

    class Meta:
        model = Tag
        fields = ['name', 'owner', 'type_of_tag', 'description']
        labels = {
            'name': 'Name',
            'type_of_tag': 'Art des Tags',
            'description': 'Beschreibung',
        }

    def clean_name(self):
        name = self.cleaned_data.get('name')

        if any(character.isspace() for character in name):
            raise forms.ValidationError(
                "Der Name des Tags darf keine Leerzeichen, Tabulator-Zeichen, "
                "Zeilenumbrüche oder Ähnliches enthalten."
            )

        return name

diary/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from .forms import CreateDiaryOwnerForm, DiaryEntryForm, LocationForm, TagForm
from .models import DiaryEntry, DiaryOwner, Location, Tag


@login_required
def get_locations(request):
    queried_owner_handle = request.GET.get('diaryOwner', '')
    locations = []

    if queried_owner_handle:
        diary_owner = get_object_or_404(DiaryOwner,
                                        handle=queried_owner_handle)
        for location in Location.objects.filter(owner=diary_owner):
            locations.append((location.id, location.name))

    return JsonResponse({'locations': locations})


@login_required
def get_tags(request):
    queried_owner_handle = request.GET.get('diaryOwner', '')
    tags = []

    if queried_owner_handle:
        diary_owner = get_object_or_404(DiaryOwner,
                                        handle=queried_owner_handle)
        for tag in Tag.objects.filter(owner=diary_owner):
            tags.append((tag.id, tag.name))

    return JsonResponse({'tags': tags})


@login_required
def recent_changes_view(request):
    entries = DiaryEntry.objects.order_by('-creation_time')
    context = {'entries': entries}
    return render(request, 'diary/recent_changes.html', context)


@login_required
def new_diary_view(request):
    if request.method == 'POST':
        form = CreateDiaryOwnerForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('diary:index')
    else:
        form = CreateDiaryOwnerForm()

    return render(request, 'diary/new_diary.html', {'form': form})


@login_required
def new_entry_view(request):
    if request.method == 'POST':
        form = DiaryEntryForm(request.POST)
        if form.is_valid():
            entry = form.save(commit=False)
            entry.creation_time = datetime.datetime.now()
            entry.save()
            form.save_m2m()

            return HttpResponseRedirect(reverse('diary:entry_detail',
                                        args=[entry.owner.handle, entry.date]))
    else:
        form = DiaryEntryForm()

    return render(request, 'diary/new_entry.html', {'form': form})


@login_required
def new_location_view(request):
    if request.method == 'POST':
        form = LocationForm(request.POST)
        if form.is_valid():
            location = form.save()

            return HttpResponseRedirect(reverse('diary:location_detail',
                                        args=[location.slug]))
    else:
        form = LocationForm()

    return render(request, 'diary/new_location.html', {'form': form})


@login_required
def new_tag_view(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            tag = form.save()

            return HttpResponseRedirect(reverse('diary:tag_detail',
                                        args=[tag.name]))
    else:
        form = TagForm()

    return render(request, 'diary/new_tag.html', {'form': form})


@login_required
def edit_owner_view(request, handle):
    owner = get_object_or_404(DiaryOwner, handle=handle)
    if request.method == 'POST':
        form = CreateDiaryOwnerForm(request.POST, instance=owner)
        if form.is_valid():
            owner = form.save()

            return HttpResponseRedirect(reverse('diary:owner_detail',
                                        args=[owner.handle]))
    else:
        form = CreateDiaryOwnerForm(instance=owner)

    return render(request, 'diary/new_diary.html', {'form': form})


@login_required
def delete_owner_view(request, handle):
    owner = get_object_or_404(DiaryOwner, handle=handle)
    owner.delete()

    return redirect('diary:owner_list')


@login_required
def edit_entry_view(request, handle, date):
    entry = get_object_or_404(DiaryEntry, date=date, owner__handle=handle)
    owner = get_object_or_404(DiaryOwner, handle=handle)
    if request.method == 'POST':
        form = DiaryEntryForm(request.POST, instance=entry)
        if form.is_valid():
            entry = form.save()

            return HttpResponseRedirect(reverse('diary:entry_detail',
                                        args=[entry.owner.handle, entry.date]))
    else:
        form = DiaryEntryForm(instance=entry, initial={'owner': owner.handle})

    return render(request, 'diary/new_entry.html', {'form': form})


@login_required
def delete_entry_view(request, handle, date):
    entry = get_object_or_404(DiaryEntry, date=date, owner__handle=handle)
    entry.delete()

    return redirect('diary:entry_list')


@login_required
def edit_location_view(request, slug):
    location = get_object_or_404(Location, slug=slug)
    if request.method == 'POST':
        form = LocationForm(request.POST, instance=location)
        if form.is_valid():
            location = form.save()

            return HttpResponseRedirect(reverse('diary:location_detail',
                                        args=[location.slug]))
    else:
        form = LocationForm(instance=location)

    return render(request, 'diary/new_location.html', {'form': form})


@login_required
def delete_location_view(request, name):
    location = get_object_or_404(Location, slug=name)
    location.delete()

    return redirect('diary:location_list')


@login_required
def edit_tag_view(request, name):
    tag = get_object_or_404(Tag, name=name)
    if request.method == 'POST':
        form = TagForm(request.POST, instance=tag)
        if form.is_valid():
            tag = form.save()

            return HttpResponseRedirect(reverse('diary:tag_detail',
                                        args=[tag.name]))
    else:
        form = TagForm(instance=tag)

    return render(request, 'diary/new_tag.html', {'form': form})


@login_required
def delete_tag_view(request, name):
    tag = get_object_or_404(Tag, name=name)
    tag.delete()

    return redirect('diary:tag_list')


@login_required
def owner_list_view(request):
    owners = DiaryOwner.objects.all()
    context = {'owners': owners}

    return render(request, 'diary/owner_list.html', context)


@login_required
def entry_list_view(request):
    entries = DiaryEntry.objects.all()
    context = {'entries': entries}

    return render(request, 'diary/entry_list.html', context)


@login_required
def location_list_view(request):
    locations = Location.objects.all()
    context = {'locations': locations}

    return render(request, 'diary/location_list.html', context)


@login_required
def tag_list_view(request):
    tags = Tag.objects.all()
    context = {'tags': tags}

    return render(request, 'diary/tag_list.html', context)


@login_required
def owner_detail_view(request, handle):
    owner = get_object_or_404(DiaryOwner, handle=handle)
    entries = DiaryEntry.objects.filter(owner__handle=handle)
    context = {'owner': owner, 'entries': entries}

    return render(request, 'diary/owner_detail.html', context)


@login_required
def entry_detail_view(request, handle, date):
    entry = get_object_or_404(DiaryEntry, date=date, owner__handle=handle)
    context = {'entry': entry}

    return render(request, 'diary/entry_detail.html', context)


@login_required
def location_detail_view(request, slug):
    location = get_object_or_404(Location, slug=slug)
    context = {'location': location}

    return render(request, 'diary/location_detail.html', context)


@login_required
def tag_detail_view(request, name):
    tag = get_object_or_404(Tag, name=name)
    context = {'tag': tag}

    return render(request, 'diary/tag_detail.html', context)

diary/templates/diary/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Tagebuch</title>{% endblock %}
  {% block header %}{% endblock %}
  <link rel="stylesheet" type="text/css" href="{% static 'diary/style.css' %}"/>
  <link rel="shortcut icon" type"image/png" href="{% static 'diary/images/diary_icon.png' %}"/>
</head>

<body id="{% block body_id %}{% endblock %}">
  <div id="wrapper">
    <div id="header"></div>
    <div id="nav">
      <ul id="navbar">
        <li class="navbar"><a id="home-nav" href="{% url 'diary:index' %}">Home</a></li>
        <br>
        <li class="navbar"><a id="new-diary-nav" href="{% url 'diary:new_diary' %}">Neues Tagebuch</a></li>
        <li class="navbar"><a id="new-entry-nav" href="{% url 'diary:new_entry' %}">Neuer Eintrag</a></li>
        <li class="navbar"><a id="new-location-nav" href="{% url 'diary:new_location' %}">Neuer Ort</a></li>
        <li class="navbar"><a id="new-tag-nav" href="{% url 'diary:new_tag' %}">Neues Tag</a></li>
        <br>
        <li class="navbar"><a id="owners-nav" href="{% url 'diary:owner_list' %}">Tagebücher</a></li>
        <li class="navbar"><a id="entries-nav" href="{% url 'diary:entry_list' %}">Einträge</a></li>
        <li class="navbar"><a id="locations-nav" href="{% url 'diary:location_list' %}">Orte</a></li>
        <li class="navbar"><a id="tags-nav" href="{% url 'diary:tag_list' %}">Tags</a></li>
        <br>
        <li class="navbar"><a href="{% url 'logout' %}">Logout</a></li>
      </ul>
    </div>
  <div id="main-content">
  {% block content %}{% endblock %}
  </div>
</body>
</html>

diary/templates/diary/entry_detail.html
{% extends "diary/base.html" %}

{% block body_id %}body-entries{% endblock %}

{% block content %}
  <h1>{{ entry.title }}</h1>

  <div>
    <table>
      <tr><td>Tagebuch von:</td><td><a class="owner" href="{% url 'diary:owner_detail' entry.owner.handle %}">{{ entry.owner }}</a></td></tr>
      <tr><td>Datum:</td><td>{{ entry.date }}</td></tr>
      <tr><td>Wochentag:</td><td>{{ entry.weekday }}</td></tr>
      <tr>
        <td>Tags:</td>
        <td>
          {% if entry.tags.all %}
          {% for tag in entry.tags.all %}
          <span class="entry-tag">{{ tag }}</span>
          {% endfor %}
          {% else %}
          -
          {% endif %}
        </td>
      </tr>
      <tr>
        <td>Ort(e):</td>
        <td>
          {% if entry.locations.all %}
          {% for location in entry.locations.all %}
          <span class="location">{{ location }}</span>
          {% endfor %}
          {% else %}
          -
          {% endif %}
        </td>
      </tr>
    </table>
    <div class="entry">{{ entry.content|safe }}</div>
    <div class="action-bar">
      <a href="{% url 'diary:edit_entry' entry.owner.handle entry.date %}">Eintrag bearbeiten</a>
      <a href="{% url 'diary:delete_entry' entry.owner.handle entry.date %}">Eintrag löschen</a>
    </div>
  </div>
{% endblock %}

diary/templates/diary/entry_list.html
{% extends "diary/base.html" %}

{% block body_id %}body-entries{% endblock %}

{% block content %}
  <h1>Tagebuch-Einträge</h2>
  {% if entries %}
      <ul>
      {% for entry in entries %}
      <li><a class="list" href="{% url 'diary:entry_detail' entry.owner.handle entry.date %}"><strong>{{ entry.owner.str_short}}</strong>: {{ entry }}</a></li>
      {% endfor %}
      </ul>
  {% else %}
      <p>Keine Einträge vorhanden.</p>
  {% endif %}
{% endblock %}

diary/templates/diary/location_detail.html
{% extends "diary/base.html" %}

{% block body_id %}body-locations{% endblock %}

{% block content %}
  <h1>{{ location.name }}</h1>

  <div>
    <table>
      <tr><td>Tagebuch von:</td><td>{{ location.owner }}</td></tr>
      <tr><td>Längengrad:</td><td>{{ location.longitude }}</td></tr>
      <tr><td>Breitengrad:</td><td>{{ location.latitude }}</td></tr>
      <tr><td>PLZ:</td><td>{{ location.postal_code }}</td></tr>
      <tr><td>Straße:</td><td>{{ location.street }}</td></tr>
      <tr><td>Hausnummer:</td><td>{{ location.house_number }}</td></tr>
      <tr><td>Ort:</td><td>{{ location.city }}</td></tr>
      <tr><td>Beschreibung:</td><td>{{ location.description }}</td></tr>
    </table>
  </div>
  <div class="action-bar">
    <a href="{% url 'diary:edit_location' location.slug %}">Ort bearbeiten</a>
    <a href="{% url 'diary:delete_location' location.slug %}">Ort löschen</a>
  </div>
{% endblock %}

diary/templates/diary/location_list.html
{% extends "diary/base.html" %}

{% block body_id %}body-locations{% endblock %}

{% block content %}
  <h1>Orte</h2>
  {% if locations %}
      <ul>
      {% for location in locations %}
      <li><a class="list" href="{% url 'diary:location_detail' location.slug %}">{{ location }} ({{ location.owner }})</a></li>
      {% endfor %}
      </ul>
  {% else %}
      <p>Keine Orte vorhanden.</p>
  {% endif %}
{% endblock %}

diary/templates/diary/new_diary.html
{% extends "diary/base.html" %}

{% block body_id %}body-new-diary{% endblock %}

{% block content %}
<h1>Neues Tagebuch für</h1>
<form method="post">
  {% csrf_token %}
  <table>
  {{ form }}
  </table>
  <button type="submit">Abschicken</button>
{% endblock %}

diary/templates/diary/new_entry.html
{% extends "diary/base.html" %}

{% block body_id %}body-new-entry{% endblock %}

{% block header %}
  {% load static %}
  {{ form.media }}
{% endblock %}

{% block content %}
<script src="{% static "diary/js/webdiary.js"%}" defer></script>
<h1>Neuer Eintrag</h1>
<form method="post">
  {% csrf_token %}
  <table>
  {{ form }}
  </table>
  <button type="submit">Abschicken</button>
{% endblock %}

diary/templates/diary/new_location.html
{% extends "diary/base.html" %}

{% block body_id %}body-new-location{% endblock %}

{% block content %}
<h1>Neuer Ort</h1>
<form method="post">
  {% csrf_token %}
  <table>
  {{ form }}
  </table>
  <button type="submit">Abschicken</button>
{% endblock %}

diary/templates/diary/new_tag.html
{% extends "diary/base.html" %}

{% block body_id %}body-new-tag{% endblock %}

{% block content %}
<h1>Neues Tag</h1>
<form method="post">
  {% csrf_token %}

  {{ form.non_field_errors }}
  {% for hidden_field in form.hidden_fields %}
  {{ hidden_field.errors }}
  {{ hidden_field }}
  {% endfor %}

  <table>
    {% for field in form.visible_fields %}
    <tr>
      <th>{{ field.label_tag }}</th>
      <td>
        {{ field.errors }}
        {% if field.name == "name" %}#{% endif %}
        {{ field }}
      </td>
    </tr>
    {% endfor %}
  </table>

  <button type="submit">Abschicken</button>
{% endblock %}

diary/templates/diary/owner_detail.html
{% extends "diary/base.html" %}

{% block body_id %}body-owners{% endblock %}

{% block content %}
  <h1>Tagebuch von</h1>
  <h2>{{ owner }}</h2>

  <div>
    <h3>Persönliche Daten</h3>
    <table>
      <tr><td>Geburtstag:</td><td>{{ owner.birthday }}</td></tr>
      <tr>
        <td>Zeit der Geburt:</td>
        <td>
          {% if owner.time_of_birth %}
          {{ owner.time_of_birth }}
          {% else %}
          -
          {% endif %}
        </td>
      </tr>
      <tr>
        <td>Geburtsort:</td>
        <td>
          {% if owner.place_of_birth %}
          {{ owner.place_of_birth }}
          {% else %}
          -
          {% endif %}
        </td>
      </tr>
    </table>
    <div class="action-bar">
      <a href="{% url 'diary:edit_owner' owner.handle %}">{{ owner.first_name }} bearbeiten</a>
      <a href="{% url 'diary:delete_owner' owner.handle %}">{{ owner.first_name }} löschen</a>
    </div>
  </div>
  <div>
    <h3>Tagebuch-Einträge</h3>
    {% if entries %}
    <ul>
    {% for entry in entries %}
      <li><a class="list" href="{% url 'diary:entry_detail' owner.handle entry.date %}">{{ entry }}</a></li>
    {% endfor %}
    </ul>
    {% else %}
    <p>Keine Einträge für {{ owner }} vorhanden.</p>
    {% endif %}
  </div>
{% endblock %}

diary/templates/diary/owner_list.html
{% extends "diary/base.html" %}

{% block body_id %}body-owners{% endblock %}

{% block content %}
  <h1>Tagebücher</h2>
  {% if owners %}
      <ul>
        {% for owner in owners %}
        <li><a class="list" href="{% url 'diary:owner_detail' owner.handle %}">{{ owner }}, {{ owner.birthday }}</a></li>
        {% endfor %}
      </ul>
  {% else %}
      <p>Keine Tagebücher vorhanden.</p>
  {% endif %}
{% endblock %}

diary/templates/diary/recent_changes.html
{% extends "diary/base.html" %}

{% block body_id %}body-home{% endblock %}

{% block content %}
  <h1>Kürzlich erstellte Einträge</h2>
  {% if entries %}
    <ul>
    {% for entry in entries %}
    <li><a class="list" href="{% url 'diary:entry_detail' entry.owner.handle entry.date %}">({{ entry.creation_time }}) <strong>{{ entry.owner.str_short}}</strong>: {{ entry }}</a></li>
    {% endfor %}
    </ul>
  {% else %}
    <p>Keine Einträge vorhanden.</p>
  {% endif %}
{% endblock %}

diary/templates/diary/tag_detail.html
{% extends "diary/base.html" %}

{% block body_id %}body-tags{% endblock %}

{% block content %}
  <h1>{{ tag }}</h1>

  <div>
    <table>
      <tr><td>Tagebuch von:</td><td>{{ tag.owner }}</td></tr>
      <tr><td>Art des Tags:</td><td>{{ tag.type_of_tag }}</td></tr>
      <tr><td>Beschreibung:</td><td>{{ tag.description }}</td></tr>
    </table>
  </div>
  <div class="action-bar">
    <a href="{% url 'diary:edit_tag' tag.name %}">Tag bearbeiten</a>
    <a href="{% url 'diary:delete_tag' tag.name %}">Tag löschen</a>
  </div>
{% endblock %}

diary/templates/diary/tag_list.html
{% extends "diary/base.html" %}

{% block body_id %}body-tags{% endblock %}

{% block content %}
  <h1>Tags</h2>
  {% if tags %}
      <ul>
      {% for tag in tags %}
      <li><a class="list" href="{% url 'diary:tag_detail' tag.name %}">{{ tag }} ({{ tag.owner }})</a></li>
      {% endfor %}
      </ul>
  {% else %}
      <p>Keine Tags vorhanden.</p>
  {% endif %}
{% endblock %}